<?php

namespace App\Http\Requests;

use App\Models\User;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Password;
use Illuminate\Validation\Rules;

class PasswordRequest extends FormRequest
{

    public function authorize()
    {
        return true;
    }



    public function failedValidation(Validator $validator)
    {
        session()->flash('updateFailed');
        parent::failedValidation($validator); // TODO: Change the autogenerated stub

    }

    public function rules()
    {
        return [
            'password' => ['required','min:8', function ($attribute, $value, $fail) {
                if (!Hash::check($value, Auth::user()->password)) {
                    session()->flash('updateFailed');
                    $fail('Текущий пароль введен неверно');
                }
            }, ],
            'new_password' => 'required|min:8',
            'new_password_confirmation' => 'required|same:new_password'
        ];
    }
}
